import { RobotPartDefinition } from '../types/robot';

export const ROBOT_PARTS_CATALOG: RobotPartDefinition[] = [
  // ================= 1. CONTROLLERS & BRAINS =================
  {
    id: 'arduino_uno',
    name: 'Arduino Uno R3',
    category: 'controllers',
    description: 'Standard ATmega328P microcontroller board with 14 digital I/O, 6 PWM, and 6 analog inputs.',
    dimensions: [68.6, 12, 53.4],
    defaultColor: '#00878F',
    approxPriceUsd: 12.0,
    tags: ['arduino', 'uno', 'atmega328p', 'mcu', 'controller', '5v', 'main board'],
    specs: {
      voltage: '5V (Input 7-12V)',
      current: '500mA max (USB)',
      weight: '25g',
      interface: 'Digital, PWM, Analog, I2C, SPI, UART',
      mcu: 'ATmega328P @ 16MHz',
    },
    meshType: 'arduino_uno',
    pins: [
      { id: '5V', name: '5V', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: '3V3', name: '3.3V', type: 'power-3v3', position: 'bottom', color: '#F97316' },
      { id: 'GND_1', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'GND_2', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'VIN', name: 'VIN', type: 'power-5v', position: 'bottom', color: '#DC2626' },
      { id: 'A0', name: 'A0', type: 'analog', position: 'bottom', color: '#3B82F6' },
      { id: 'A1', name: 'A1', type: 'analog', position: 'bottom', color: '#3B82F6' },
      { id: 'A2', name: 'A2', type: 'analog', position: 'bottom', color: '#3B82F6' },
      { id: 'A3', name: 'A3', type: 'analog', position: 'bottom', color: '#3B82F6' },
      { id: 'A4', name: 'A4/SDA', type: 'i2c', position: 'bottom', color: '#10B981' },
      { id: 'A5', name: 'A5/SCL', type: 'i2c', position: 'bottom', color: '#10B981' },
      { id: 'D0', name: 'D0/RX', type: 'uart', position: 'top', color: '#8B5CF6' },
      { id: 'D1', name: 'D1/TX', type: 'uart', position: 'top', color: '#8B5CF6' },
      { id: 'D2', name: 'D2', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'D3', name: 'D3~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D4', name: 'D4', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'D5', name: 'D5~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D6', name: 'D6~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D7', name: 'D7', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'D8', name: 'D8', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'D9', name: 'D9~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D10', name: 'D10~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D11', name: 'D11~PWM', type: 'pwm', position: 'top', color: '#F59E0B' },
      { id: 'D12', name: 'D12', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'D13', name: 'D13(LED)', type: 'digital', position: 'top', color: '#EAB308' },
      { id: 'GND_3', name: 'GND', type: 'ground', position: 'top', color: '#1F2937' },
    ]
  },
  {
    id: 'arduino_mega',
    name: 'Arduino Mega 2560 R3',
    category: 'controllers',
    description: 'High-pinout ATmega2560 controller with 54 digital I/O, 16 analog inputs, 4 UART serial ports for complex multi-joint robotics.',
    dimensions: [101.5, 14, 53.3],
    defaultColor: '#005C61',
    approxPriceUsd: 22.0,
    tags: ['arduino', 'mega', '2560', '54 pins', 'robotic arm', '3d printer'],
    specs: {
      voltage: '5V (Input 7-12V)',
      mcu: 'ATmega2560 @ 16MHz',
      flash: '256 KB',
      sram: '8 KB',
      ioPins: '54 Digital, 16 Analog',
    },
    meshType: 'arduino_mega',
    pins: [
      { id: '5V', name: '5V', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'SDA', name: 'SDA (20)', type: 'i2c', position: 'top', color: '#10B981' },
      { id: 'SCL', name: 'SCL (21)', type: 'i2c', position: 'top', color: '#10B981' },
      { id: 'TX1', name: 'TX1 (18)', type: 'uart', position: 'top', color: '#8B5CF6' },
      { id: 'RX1', name: 'RX1 (19)', type: 'uart', position: 'top', color: '#8B5CF6' },
    ]
  },
  {
    id: 'arduino_nano',
    name: 'Arduino Nano V3',
    category: 'controllers',
    description: 'Miniature breadboard-friendly ATmega328P microcontroller with Mini-USB.',
    dimensions: [45, 8, 18],
    defaultColor: '#00878F',
    approxPriceUsd: 5.5,
    tags: ['arduino', 'nano', 'breadboard', 'compact', 'mini'],
    specs: {
      voltage: '5V (VIN 7-12V)',
      current: '19mA',
      weight: '7g',
      interface: 'Digital, PWM, Analog, I2C, SPI',
      mcu: 'ATmega328P @ 16MHz',
    },
    meshType: 'arduino_nano',
    pins: [
      { id: 'D2', name: 'D2', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'D3', name: 'D3~', type: 'pwm', position: 'left', color: '#F59E0B' },
      { id: 'D4', name: 'D4', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'D5', name: 'D5~', type: 'pwm', position: 'left', color: '#F59E0B' },
      { id: '5V', name: '5V', type: 'power-5v', position: 'right', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'right', color: '#1F2937' },
      { id: 'A4', name: 'A4(SDA)', type: 'i2c', position: 'right', color: '#10B981' },
      { id: 'A5', name: 'A5(SCL)', type: 'i2c', position: 'right', color: '#10B981' },
    ]
  },
  {
    id: 'esp32_devkit',
    name: 'ESP32 DevKit V1 (Wi-Fi + BLE)',
    category: 'controllers',
    description: 'High-speed dual-core 240MHz SoC with integrated Wi-Fi 802.11 b/g/n & Bluetooth BLE 4.2.',
    dimensions: [51, 8, 28],
    defaultColor: '#1E293B',
    approxPriceUsd: 6.0,
    tags: ['esp32', 'wifi', 'bluetooth', 'iot', 'wireless', 'dual core', 'camera rover'],
    specs: {
      voltage: '3.3V / 5V (USB)',
      current: '80-240mA',
      mcu: 'Xtensa Dual-Core 32-bit LX6 @ 240MHz',
      wireless: 'Wi-Fi 2.4GHz + BLE 4.2',
    },
    meshType: 'esp32',
    pins: [
      { id: '3V3', name: '3V3', type: 'power-3v3', position: 'left', color: '#F97316' },
      { id: 'GND_1', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'D15', name: 'GPIO15', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'D2', name: 'GPIO2(LED)', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'D4', name: 'GPIO4', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'D21', name: 'GPIO21(SDA)', type: 'i2c', position: 'left', color: '#10B981' },
      { id: 'D22', name: 'GPIO22(SCL)', type: 'i2c', position: 'left', color: '#10B981' },
      { id: 'VIN', name: 'VIN(5V)', type: 'power-5v', position: 'right', color: '#EF4444' },
      { id: 'GND_2', name: 'GND', type: 'ground', position: 'right', color: '#1F2937' },
      { id: 'D13', name: 'GPIO13', type: 'digital', position: 'right', color: '#EAB308' },
      { id: 'D12', name: 'GPIO12', type: 'digital', position: 'right', color: '#EAB308' },
      { id: 'D14', name: 'GPIO14', type: 'digital', position: 'right', color: '#EAB308' },
    ]
  },
  {
    id: 'raspberry_pi_4',
    name: 'Raspberry Pi 4 Model B (4GB)',
    category: 'controllers',
    description: 'Quad-core 64-bit ARM Cortex-A72 @ 1.5GHz single-board computer for autonomous AI robotics, ROS, OpenCV computer vision.',
    dimensions: [85.6, 17, 56.5],
    defaultColor: '#059669',
    approxPriceUsd: 55.0,
    tags: ['raspberry pi', 'rpi', 'pi 4', 'linux', 'ros', 'opencv', 'ai vision'],
    specs: {
      cpu: 'Quad Core ARM Cortex-A72 @ 1.5GHz',
      ram: '4GB LPDDR4',
      ports: '2x USB 3.0, 2x USB 2.0, Gigabit Ethernet, 2x micro HDMI 4K',
      gpio: '40-pin standard header',
    },
    meshType: 'raspberry_pi',
    pins: [
      { id: '5V_PIN2', name: '5V Power', type: 'power-5v', position: 'top', color: '#EF4444' },
      { id: '3V3_PIN1', name: '3.3V Power', type: 'power-3v3', position: 'top', color: '#F97316' },
      { id: 'GND_PIN6', name: 'GND', type: 'ground', position: 'top', color: '#1F2937' },
      { id: 'SDA_PIN3', name: 'I2C1 SDA', type: 'i2c', position: 'top', color: '#10B981' },
      { id: 'SCL_PIN5', name: 'I2C1 SCL', type: 'i2c', position: 'top', color: '#10B981' },
      { id: 'TXD_PIN8', name: 'UART TXD', type: 'uart', position: 'top', color: '#8B5CF6' },
      { id: 'RXD_PIN10', name: 'UART RXD', type: 'uart', position: 'top', color: '#8B5CF6' },
    ]
  },
  {
    id: 'raspberry_pico_w',
    name: 'Raspberry Pi Pico W',
    category: 'controllers',
    description: 'Dual-core ARM Cortex M0+ microcontroller with built-in Wi-Fi and Bluetooth BLE.',
    dimensions: [51, 5, 21],
    defaultColor: '#10B981',
    approxPriceUsd: 6.0,
    tags: ['pico', 'rp2040', 'micropython', 'raspberry', 'wireless'],
    specs: {
      mcu: 'RP2040 Dual-Core @ 133MHz',
      ram: '264 KB',
      interface: '26 Multi-function GPIOs, 2x SPI, 2x I2C, 2x UART, 3x ADC',
    },
    meshType: 'raspberry_pico',
    pins: [
      { id: 'VBUS', name: 'VBUS(5V)', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: '3V3', name: '3V3 OUT', type: 'power-3v3', position: 'left', color: '#F97316' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'GP0', name: 'GP0 (UART TX)', type: 'uart', position: 'right', color: '#8B5CF6' },
      { id: 'GP1', name: 'GP1 (UART RX)', type: 'uart', position: 'right', color: '#8B5CF6' },
      { id: 'GP4', name: 'GP4 (I2C0 SDA)', type: 'i2c', position: 'right', color: '#10B981' },
      { id: 'GP5', name: 'GP5 (I2C0 SCL)', type: 'i2c', position: 'right', color: '#10B981' },
    ]
  },

  // ================= 2. ACTUATORS & MOTORS =================
  {
    id: 'servo_sg90',
    name: 'SG90 9g Micro Servo',
    category: 'actuators',
    description: 'Lightweight micro servo with 180° rotation for robotic arms, pan-tilt, and grippers.',
    dimensions: [23, 29, 12.2],
    defaultColor: '#3B82F6',
    approxPriceUsd: 2.5,
    tags: ['servo', 'sg90', 'micro', 'arm', 'gripper', 'pan tilt'],
    specs: {
      voltage: '4.8V - 6.0V',
      torque: '1.8 kg-cm @ 4.8V',
      speed: '0.1s / 60 degrees',
      weight: '9g',
    },
    meshType: 'servo_sg90',
    pins: [
      { id: 'GND', name: 'GND (Brown)', type: 'ground', position: 'bottom', color: '#78350F' },
      { id: 'VCC', name: 'VCC (Red)', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'PWM', name: 'Signal (Orange)', type: 'pwm', position: 'bottom', color: '#F97316' },
    ]
  },
  {
    id: 'servo_mg996r',
    name: 'MG996R High Torque Metal Gear Servo',
    category: 'actuators',
    description: 'High-torque metal gear servo motor capable of lifting heavy robotic arm joints and biped limbs.',
    dimensions: [40.7, 42.9, 19.7],
    defaultColor: '#1F2937',
    approxPriceUsd: 7.5,
    tags: ['servo', 'mg996r', 'metal gear', 'heavy duty', 'torque', 'robotic arm'],
    specs: {
      voltage: '4.8V - 7.2V',
      torque: '11 kg-cm @ 6.0V',
      speed: '0.17s / 60 deg',
      weight: '55g',
    },
    meshType: 'servo_mg996r',
    pins: [
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'VCC', name: 'VCC', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'PWM', name: 'Signal', type: 'pwm', position: 'bottom', color: '#F97316' },
    ]
  },
  {
    id: 'dc_gear_motor_tt',
    name: 'TT DC Gear Motor with Wheel',
    category: 'actuators',
    description: 'Dual-shaft 1:48 gear ratio DC motor paired with 65mm rubber tyre wheel.',
    dimensions: [70, 22, 37],
    defaultColor: '#EAB308',
    approxPriceUsd: 3.2,
    tags: ['motor', 'dc motor', 'wheel', 'tt motor', 'gearbox', 'rover', 'car'],
    specs: {
      voltage: '3V - 6V DC',
      speed: '200 RPM @ 6V',
      current: '150mA (no load), 800mA (stall)',
    },
    meshType: 'dc_gear_motor',
    pins: [
      { id: 'M_POS', name: 'Motor +', type: 'motor-out', position: 'right', color: '#EF4444' },
      { id: 'M_NEG', name: 'Motor -', type: 'motor-out', position: 'right', color: '#1F2937' },
    ]
  },
  {
    id: 'stepper_nema17',
    name: 'NEMA 17 High-Torque Stepper Motor',
    category: 'actuators',
    description: 'Bipolar 1.8° step angle (200 steps/rev) motor for CNC machines, 3D printers, and precision linear slides.',
    dimensions: [42, 42, 40],
    defaultColor: '#334155',
    approxPriceUsd: 14.0,
    tags: ['stepper', 'nema 17', 'precision', '3d printer', 'cnc', 'linear'],
    specs: {
      stepAngle: '1.8 degrees',
      holdingTorque: '45 N-cm (63.7 oz-in)',
      ratedCurrent: '1.5A per phase',
      weight: '280g',
    },
    meshType: 'stepper_motor_nema17',
    pins: [
      { id: 'A_PLUS', name: 'Coil A+', type: 'motor-out', position: 'bottom', color: '#EF4444' },
      { id: 'A_MINUS', name: 'Coil A-', type: 'motor-out', position: 'bottom', color: '#3B82F6' },
      { id: 'B_PLUS', name: 'Coil B+', type: 'motor-out', position: 'bottom', color: '#10B981' },
      { id: 'B_MINUS', name: 'Coil B-', type: 'motor-out', position: 'bottom', color: '#EAB308' },
    ]
  },
  {
    id: 'drone_brushless_motor',
    name: 'A2212 1000KV Brushless Drone Motor',
    category: 'actuators',
    description: 'Outrunner brushless motor paired with 1045 propeller for quadcopters, VTOL, and RC aircraft.',
    dimensions: [28, 28, 26],
    defaultColor: '#F59E0B',
    approxPriceUsd: 9.5,
    tags: ['brushless', 'drone', 'propeller', 'quadcopter', 'esc', 'thrust'],
    specs: {
      kv: '1000 RPM/V',
      thrust: '850g per motor',
      battery: '2S - 3S LiPo',
      weight: '47g',
    },
    meshType: 'motor_drone_brushless',
    pins: [
      { id: 'PHASE_A', name: 'Phase A', type: 'motor-out', position: 'bottom', color: '#EF4444' },
      { id: 'PHASE_B', name: 'Phase B', type: 'motor-out', position: 'bottom', color: '#EAB308' },
      { id: 'PHASE_C', name: 'Phase C', type: 'motor-out', position: 'bottom', color: '#3B82F6' },
    ]
  },
  {
    id: 'driver_l298n',
    name: 'L298N Dual H-Bridge Motor Driver',
    category: 'actuators',
    description: 'Dual H-bridge controller capable of driving two DC motors or one 4-wire stepper motor.',
    dimensions: [43, 27, 43],
    defaultColor: '#DC2626',
    approxPriceUsd: 4.5,
    tags: ['driver', 'l298n', 'h-bridge', 'motor controller', 'dual motor'],
    specs: {
      voltage: '5V - 35V DC',
      peakCurrent: '2A per bridge',
      logicVoltage: '5V',
    },
    meshType: 'driver_l298n',
    pins: [
      { id: 'VCC_12V', name: '12V Power', type: 'power-5v', position: 'left', color: '#DC2626' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: '5V_OUT', name: '5V Reg Out', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: 'IN1', name: 'IN1', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'IN2', name: 'IN2', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'IN3', name: 'IN3', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'IN4', name: 'IN4', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'ENA', name: 'ENA (Speed A)', type: 'pwm', position: 'bottom', color: '#F59E0B' },
      { id: 'ENB', name: 'ENB (Speed B)', type: 'pwm', position: 'bottom', color: '#F59E0B' },
      { id: 'OUT1', name: 'OUT1 (Motor A+)', type: 'motor-out', position: 'left', color: '#3B82F6' },
      { id: 'OUT2', name: 'OUT2 (Motor A-)', type: 'motor-out', position: 'left', color: '#3B82F6' },
      { id: 'OUT3', name: 'OUT3 (Motor B+)', type: 'motor-out', position: 'right', color: '#10B981' },
      { id: 'OUT4', name: 'OUT4 (Motor B-)', type: 'motor-out', position: 'right', color: '#10B981' },
    ]
  },
  {
    id: 'pca9685_servo_driver',
    name: 'PCA9685 16-Channel 12-Bit PWM Servo Driver',
    category: 'actuators',
    description: 'I2C controlled 16-channel PWM controller for driving multiple robot arm servos, hexapods, and animatronics.',
    dimensions: [62, 12, 25],
    defaultColor: '#1E293B',
    approxPriceUsd: 5.5,
    tags: ['pca9685', 'i2c', '16 channel', 'pwm', 'servo driver', 'hexapod', 'arm'],
    specs: {
      interface: 'I2C (Address 0x40 to 0x7F)',
      frequency: '40Hz - 1000Hz',
      resolution: '12-bit (4096 steps)',
    },
    meshType: 'driver_pca9685',
    pins: [
      { id: 'VCC', name: 'VCC (Logic)', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'SDA', name: 'SDA', type: 'i2c', position: 'left', color: '#10B981' },
      { id: 'SCL', name: 'SCL', type: 'i2c', position: 'left', color: '#10B981' },
      { id: 'V_PLUS', name: 'V+ (Servo Power)', type: 'power-5v', position: 'left', color: '#DC2626' },
    ]
  },
  {
    id: 'relay_module_5v',
    name: '5V Single Channel Optocoupler Relay Module',
    category: 'actuators',
    description: 'High-voltage switching relay capable of switching AC 250V 10A / DC 30V 10A loads with optoisolation.',
    dimensions: [50, 18, 26],
    defaultColor: '#1D4ED8',
    approxPriceUsd: 1.8,
    tags: ['relay', 'switch', 'optocoupler', 'high voltage', 'solenoid', 'pump'],
    specs: {
      triggerVoltage: '5V DC (Low / High trigger jumper)',
      maxLoad: 'AC 250V 10A / DC 30V 10A',
    },
    meshType: 'relay_module',
    pins: [
      { id: 'VCC', name: 'VCC', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'IN', name: 'IN (Trigger)', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'NO', name: 'Normally Open (NO)', type: 'motor-out', position: 'right', color: '#10B981' },
      { id: 'COM', name: 'Common (COM)', type: 'motor-out', position: 'right', color: '#3B82F6' },
      { id: 'NC', name: 'Normally Closed (NC)', type: 'motor-out', position: 'right', color: '#EF4444' },
    ]
  },

  // ================= 3. SENSORS =================
  {
    id: 'sensor_ultrasonic_hcsr04',
    name: 'HC-SR04 Ultrasonic Distance Sensor',
    category: 'sensors',
    description: 'Sonar distance measuring module providing 2cm to 400cm obstacle sensing.',
    dimensions: [45, 20, 15],
    defaultColor: '#0284C7',
    approxPriceUsd: 2.0,
    tags: ['ultrasonic', 'sonar', 'hcsr04', 'distance', 'obstacle avoidance'],
    specs: {
      voltage: '5V DC',
      frequency: '40kHz',
      range: '2cm - 400cm',
      accuracy: '3mm',
    },
    meshType: 'sensor_ultrasonic',
    pins: [
      { id: 'VCC', name: 'VCC', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'TRIG', name: 'TRIG (Trigger)', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'ECHO', name: 'ECHO (Echo Out)', type: 'digital', position: 'bottom', color: '#3B82F6' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
    ]
  },
  {
    id: 'sensor_lidar_tfluna',
    name: 'TF-Luna Micro LiDAR ToF Sensor',
    category: 'sensors',
    description: 'Time-of-Flight (ToF) 850nm infrared laser LiDAR with 0.2m - 8m range and high 100Hz refresh rate for drone altitude & mapping.',
    dimensions: [35, 13, 21],
    defaultColor: '#111827',
    approxPriceUsd: 26.0,
    tags: ['lidar', 'laser', 'tof', 'distance', 'mapping', 'slam', 'drone altitude'],
    specs: {
      range: '0.2m - 8m',
      frequency: '100Hz',
      interface: 'UART / I2C',
      accuracy: '±6cm @ (0.2-3m)',
    },
    meshType: 'sensor_lidar',
    pins: [
      { id: 'VCC', name: '5V', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'RX', name: 'RXD', type: 'uart', position: 'left', color: '#8B5CF6' },
      { id: 'TX', name: 'TXD', type: 'uart', position: 'left', color: '#8B5CF6' },
    ]
  },
  {
    id: 'esp32_cam_module',
    name: 'ESP32-CAM Video & AI Vision Module',
    category: 'sensors',
    description: 'Ultra-small OV2640 2-Megapixel camera module with built-in flash LED, MicroSD card slot and Wi-Fi streaming.',
    dimensions: [40, 12, 27],
    defaultColor: '#1E293B',
    approxPriceUsd: 8.5,
    tags: ['camera', 'esp32 cam', 'video', 'stream', 'vision', 'opencv', 'surveillance'],
    specs: {
      camera: 'OV2640 (1600x1200 UXGA)',
      flash: 'Ultra-bright white onboard LED',
      storage: 'MicroSD TF slot up to 4GB',
    },
    meshType: 'sensor_camera_ov2640',
    pins: [
      { id: '5V', name: '5V Power', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'U0T', name: 'U0TXD', type: 'uart', position: 'bottom', color: '#8B5CF6' },
      { id: 'U0R', name: 'U0RXD', type: 'uart', position: 'bottom', color: '#8B5CF6' },
    ]
  },
  {
    id: 'sensor_mpu6050',
    name: 'MPU6050 6-Axis Gyro & Accelerometer',
    category: 'sensors',
    description: '3-axis accelerometer and 3-axis gyroscope with integrated Digital Motion Processor (DMP) for self-balancing robots.',
    dimensions: [20, 3, 16],
    defaultColor: '#047857',
    approxPriceUsd: 2.8,
    tags: ['gyro', 'accelerometer', 'mpu6050', 'imu', 'balancing', 'angle', 'drone stabilization'],
    specs: {
      voltage: '3.3V - 5V',
      communication: 'I2C Interface',
      gyroRange: '±250, 500, 1000, 2000 °/s',
      accelRange: '±2, 4, 8, 16 g',
    },
    meshType: 'sensor_mpu6050',
    pins: [
      { id: 'VCC', name: 'VCC', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'SCL', name: 'SCL', type: 'i2c', position: 'bottom', color: '#10B981' },
      { id: 'SDA', name: 'SDA', type: 'i2c', position: 'bottom', color: '#10B981' },
    ]
  },
  {
    id: 'sensor_ir_line_tracker',
    name: 'TCRT5000 IR Line Tracker Sensor',
    category: 'sensors',
    description: 'Infrared reflective photo-transistor sensor for black/white line tracking.',
    dimensions: [32, 10, 14],
    defaultColor: '#1E293B',
    approxPriceUsd: 1.2,
    tags: ['ir', 'line tracker', 'tcrt5000', 'infrared', 'line follower'],
    specs: {
      voltage: '3.3V - 5V',
      detectionDistance: '1mm - 25mm',
      output: 'Digital (0/1) & Analog',
    },
    meshType: 'sensor_ir_tracker',
    pins: [
      { id: 'VCC', name: 'VCC', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
      { id: 'DO', name: 'DO', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'AO', name: 'AO', type: 'analog', position: 'bottom', color: '#3B82F6' },
    ]
  },
  {
    id: 'sensor_pir_motion',
    name: 'HC-SR501 Pyroelectric PIR Motion Sensor',
    category: 'sensors',
    description: 'Infrared passive motion detection sensor with fresnel lens for security bots and intruder alarms.',
    dimensions: [32, 25, 24],
    defaultColor: '#E2E8F0',
    approxPriceUsd: 2.2,
    tags: ['pir', 'motion', 'human detection', 'security', 'sensor'],
    specs: {
      voltage: '4.5V - 20V',
      detectDistance: 'Up to 7 meters',
      detectAngle: '< 100 degrees cone',
    },
    meshType: 'sensor_pir',
    pins: [
      { id: 'VCC', name: 'VCC (5V)', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'OUT', name: 'OUT (Digital)', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
    ]
  },
  {
    id: 'sensor_dht22_temp',
    name: 'DHT22 Digital Temperature & Humidity Sensor',
    category: 'sensors',
    description: 'High-accuracy digital capacitive sensor for temperature (-40 to 80°C) and humidity (0-100%).',
    dimensions: [27, 15, 8],
    defaultColor: '#FFFFFF',
    approxPriceUsd: 3.5,
    tags: ['dht22', 'temperature', 'humidity', 'weather', 'climate', 'environment'],
    specs: {
      humidityRange: '0-100% RH (±2%)',
      tempRange: '-40 to 80°C (±0.5°C)',
      samplingRate: '0.5 Hz (every 2s)',
    },
    meshType: 'sensor_dht22',
    pins: [
      { id: 'VCC', name: 'VCC (3.3-5V)', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'DATA', name: 'DATA', type: 'digital', position: 'bottom', color: '#EAB308' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'bottom', color: '#1F2937' },
    ]
  },

  // ================= 4. DISPLAYS & INDICATORS =================
  {
    id: 'display_oled_096',
    name: '0.96" I2C OLED Display (128x64 SSD1306)',
    category: 'displays',
    description: 'High-contrast monochrome graphic OLED display for robot faces, battery status, telemetry stats.',
    dimensions: [27, 4, 27],
    defaultColor: '#0F172A',
    approxPriceUsd: 3.8,
    tags: ['oled', 'display', 'screen', 'ssd1306', 'i2c', 'robot eyes', 'face'],
    specs: {
      resolution: '128 x 64 pixels',
      driver: 'SSD1306',
      interface: 'I2C (0x3C)',
      power: '0.08W (Full screen lit)',
    },
    meshType: 'display_oled_096',
    pins: [
      { id: 'GND', name: 'GND', type: 'ground', position: 'top', color: '#1F2937' },
      { id: 'VCC', name: 'VCC (3.3-5V)', type: 'power-5v', position: 'top', color: '#EF4444' },
      { id: 'SCL', name: 'SCL', type: 'i2c', position: 'top', color: '#10B981' },
      { id: 'SDA', name: 'SDA', type: 'i2c', position: 'top', color: '#10B981' },
    ]
  },
  {
    id: 'display_rgb_matrix_8x8',
    name: '8x8 WS2812B NeoPixel RGB Matrix',
    category: 'displays',
    description: '64 individually addressable RGB LEDs for expressive robot eyes, animated emojis, and status effects.',
    dimensions: [65, 3, 65],
    defaultColor: '#000000',
    approxPriceUsd: 6.5,
    tags: ['neopixel', 'ws2812b', 'rgb', 'led matrix', 'eyes', 'emoji', 'colors'],
    specs: {
      leds: '64x WS2812B 5050 RGB',
      colors: '16.7 Million 24-bit TrueColor',
      interface: 'Single Digital Pin (FastLED / Adafruit NeoPixel)',
    },
    meshType: 'display_matrix_rgb',
    pins: [
      { id: '5V', name: '5V Power', type: 'power-5v', position: 'left', color: '#EF4444' },
      { id: 'DIN', name: 'DIN (Data In)', type: 'digital', position: 'left', color: '#EAB308' },
      { id: 'GND', name: 'GND', type: 'ground', position: 'left', color: '#1F2937' },
    ]
  },

  // ================= 5. STRUCTURAL & CHASSIS =================
  {
    id: 'chassis_2wd_acrylic',
    name: '2WD Smart Robot Acrylic Chassis Plate',
    category: 'structural',
    description: 'Laser-cut acrylic main robot platform with pre-drilled holes for motors, batteries, and Arduino.',
    dimensions: [210, 3, 150],
    defaultColor: '#0EA5E9',
    approxPriceUsd: 8.0,
    tags: ['chassis', '2wd', 'acrylic', 'platform', 'base', 'frame', 'plate'],
    specs: {
      material: 'Clear Cast Acrylic Plate (3mm)',
      loadCapacity: '1.5 kg',
    },
    meshType: 'chassis_2wd',
  },
  {
    id: 'chassis_4wd_aluminum',
    name: '4WD Heavy Duty Aluminum Chassis (Dual-Deck)',
    category: 'structural',
    description: 'Rugged anodized dual-deck aluminum platform for all-terrain rovers, heavy payloads, and LiDAR rigs.',
    dimensions: [260, 40, 180],
    defaultColor: '#475569',
    approxPriceUsd: 18.0,
    tags: ['chassis', '4wd', 'aluminum', 'heavy duty', 'dual deck', 'rover base'],
    specs: {
      material: 'Anodized Aluminum Alloy',
      loadCapacity: '4.5 kg',
    },
    meshType: 'chassis_4wd',
  },
  {
    id: 'drone_frame_x450',
    name: 'F450 Carbon Fiber Quadcopter Frame',
    category: 'structural',
    description: '450mm wheelbase lightweight quadcopter frame with integrated PCB power distribution board.',
    dimensions: [450, 60, 450],
    defaultColor: '#1E293B',
    approxPriceUsd: 19.0,
    tags: ['drone', 'quadcopter', 'frame', 'f450', 'carbon fiber', 'vtol'],
    specs: {
      wheelbase: '450mm',
      weight: '280g',
      arms: 'Ultra-strength PA66+30GF',
    },
    meshType: 'chassis_drone_x',
  },
  {
    id: 'wheel_rubber_65mm',
    name: '65mm High-Grip Rubber Tyre Wheel',
    category: 'structural',
    description: 'Tire wheel with textured silicone rubber tread for TT gear motors.',
    dimensions: [65, 27, 65],
    defaultColor: '#0F172A',
    approxPriceUsd: 1.8,
    tags: ['wheel', 'tyre', 'rubber', 'drive wheel'],
    specs: {
      diameter: '65mm',
      width: '27mm',
    },
    meshType: 'wheel_rubber',
  },
  {
    id: 'wheel_mecanum_80mm',
    name: '80mm Omni-Directional Mecanum Wheel',
    category: 'structural',
    description: '45° angled roller wheel enabling holonomic movement (forward, backward, sideways strafing, spinning).',
    dimensions: [80, 38, 80],
    defaultColor: '#1E293B',
    approxPriceUsd: 7.0,
    tags: ['mecanum', 'omni', 'holonomic', 'strafe', 'wheel', 'agv'],
    specs: {
      diameter: '80mm',
      rollers: '9x High-grip TPU rubber rollers',
      loadCapacity: '15 kg per set of 4',
    },
    meshType: 'wheel_mecanum',
  },
  {
    id: 'caster_wheel_ball',
    name: 'Omni-Directional Steel Ball Caster',
    category: 'structural',
    description: 'Smooth 360-degree rotating steel ball bearing caster for 2WD balancing.',
    dimensions: [20, 15, 20],
    defaultColor: '#94A3B8',
    approxPriceUsd: 1.5,
    tags: ['caster', 'ball wheel', 'balance', 'omni', 'front wheel'],
    specs: {
      ballDiameter: '15mm',
      material: 'Chrome Plated Steel',
    },
    meshType: 'caster_wheel',
  },
  {
    id: 'pan_tilt_bracket_kit',
    name: 'Dual-Axis Pan-Tilt Servo Gimbal Bracket',
    category: 'structural',
    description: '2-DOF nylon gimbal mount for holding ultrasonic sensors, cameras, and laser pointers with SG90/MG90S servos.',
    dimensions: [40, 45, 35],
    defaultColor: '#1E293B',
    approxPriceUsd: 3.0,
    tags: ['pan tilt', 'gimbal', 'bracket', 'camera mount', 'head', 'servo mount'],
    specs: {
      axes: '2-DOF (Yaw + Pitch)',
      servoSlots: '2x SG90 / MG90S',
    },
    meshType: 'pan_tilt_bracket',
  },
  {
    id: 'robotic_arm_base',
    name: 'Robotic Arm Rotating Turntable Base',
    category: 'structural',
    description: 'Bearing-supported 360-degree rotating base for multi-axis articulated robotic arms.',
    dimensions: [100, 35, 100],
    defaultColor: '#334155',
    approxPriceUsd: 9.0,
    tags: ['arm base', 'turntable', 'rotation', 'robotic arm'],
    specs: {
      material: 'Fiberglass Reinforced PLA',
    },
    meshType: 'arm_base',
  },
  {
    id: 'robotic_arm_link',
    name: 'Robotic Arm Articulated Bracket Link',
    category: 'structural',
    description: 'Dual servo bracket link for constructing bicep, elbow, and forearm joints.',
    dimensions: [120, 25, 30],
    defaultColor: '#0284C7',
    approxPriceUsd: 4.5,
    tags: ['arm link', 'bracket', 'bicep', 'forearm', 'joint'],
    specs: {
      length: '120mm',
    },
    meshType: 'arm_link',
  },
  {
    id: 'robotic_arm_gripper',
    name: 'Mechanical Claw Gripper Mechanism',
    category: 'structural',
    description: 'Parallel gear-driven claw gripper for picking up and holding objects.',
    dimensions: [95, 45, 55],
    defaultColor: '#0F172A',
    approxPriceUsd: 6.5,
    tags: ['gripper', 'claw', 'hand', 'end effector', 'pick and place'],
    specs: {
      maxOpening: '55mm',
      gripForce: '1.2 kg',
    },
    meshType: 'arm_gripper',
  },

  // ================= 6. POWER & BREADBOARDS =================
  {
    id: 'battery_18650_dual_pack',
    name: '2x 18650 Li-Ion Battery Holder (7.4V)',
    category: 'power',
    description: 'Dual series 18650 battery holder with power toggle switch and DC barrel plug.',
    dimensions: [75, 20, 40],
    defaultColor: '#1E293B',
    approxPriceUsd: 3.5,
    tags: ['battery', '18650', 'li-ion', 'power', '7.4v', 'pack'],
    specs: {
      nominalVoltage: '7.4V (8.4V Peak)',
      capacity: '2x 2600mAh = 5200mWh',
    },
    meshType: 'battery_18650_pack',
    pins: [
      { id: 'V_POS', name: '7.4V + (Red)', type: 'power-5v', position: 'right', color: '#EF4444' },
      { id: 'V_NEG', name: 'GND - (Black)', type: 'ground', position: 'right', color: '#1F2937' },
    ]
  },
  {
    id: 'battery_lipo_3s',
    name: '3S 11.1V 2200mAh 35C LiPo Battery',
    category: 'power',
    description: 'High-discharge Lithium Polymer battery with XT60 connector for drones, high-torque robot arms, and heavy rovers.',
    dimensions: [105, 25, 34],
    defaultColor: '#475569',
    approxPriceUsd: 18.5,
    tags: ['lipo', 'battery', '3s', '11.1v', 'xt60', 'high discharge', 'drone battery'],
    specs: {
      voltage: '11.1V (3S1P)',
      capacity: '2200mAh',
      dischargeRate: '35C Constant (77A)',
      connector: 'XT60 Female',
    },
    meshType: 'battery_lipo_3s',
    pins: [
      { id: 'XT60_POS', name: '11.1V + (Red)', type: 'power-5v', position: 'right', color: '#DC2626' },
      { id: 'XT60_NEG', name: 'GND - (Black)', type: 'ground', position: 'right', color: '#1F2937' },
    ]
  },
  {
    id: 'module_buck_converter',
    name: 'LM2596 DC-DC Step-Down Buck Converter',
    category: 'power',
    description: 'High-efficiency adjustable voltage regulator module to step down 7-35V battery voltage to stable 5V for Arduino/Raspberry Pi.',
    dimensions: [43, 14, 21],
    defaultColor: '#1E40AF',
    approxPriceUsd: 2.2,
    tags: ['buck converter', 'step down', 'lm2596', 'voltage regulator', '5v regulator'],
    specs: {
      inputVoltage: '4.5V - 35V DC',
      outputVoltage: '1.25V - 30V (Adjustable trimmer)',
      maxOutputCurrent: '3A (with heatsink)',
      efficiency: 'Up to 92%',
    },
    meshType: 'module_buck_converter',
    pins: [
      { id: 'IN_POS', name: 'IN + (Vin)', type: 'power-5v', position: 'left', color: '#DC2626' },
      { id: 'IN_NEG', name: 'IN - (GND)', type: 'ground', position: 'left', color: '#1F2937' },
      { id: 'OUT_POS', name: 'OUT + (5V Reg)', type: 'power-5v', position: 'right', color: '#EF4444' },
      { id: 'OUT_NEG', name: 'OUT - (GND)', type: 'ground', position: 'right', color: '#1F2937' },
    ]
  },
  {
    id: 'breadboard_400_pts',
    name: '400-Tie Point Half-Size Solderless Breadboard',
    category: 'accessories',
    description: 'Prototyping breadboard with power distribution rails and central IC divider.',
    dimensions: [82, 9, 55],
    defaultColor: '#F8FAFC',
    approxPriceUsd: 2.0,
    tags: ['breadboard', 'proto', 'wiring', '400 points', 'solderless', 'half size'],
    specs: {
      tiePoints: '400 (300 terminal + 100 power rail)',
      pitch: 'Standard 2.54mm (0.1 in)',
    },
    meshType: 'breadboard_400',
    pins: [
      { id: 'RAIL_POS_TOP', name: 'Top Power Rail (+)', type: 'power-5v', position: 'top', color: '#EF4444' },
      { id: 'RAIL_NEG_TOP', name: 'Top Ground Rail (-)', type: 'ground', position: 'top', color: '#1F2937' },
      { id: 'RAIL_POS_BOT', name: 'Bottom Power (+)', type: 'power-5v', position: 'bottom', color: '#EF4444' },
      { id: 'RAIL_NEG_BOT', name: 'Bottom Ground (-)', type: 'ground', position: 'bottom', color: '#1F2937' },
    ]
  },
  {
    id: 'solar_panel_5v',
    name: '5V 1W Monocrystalline Solar Cell Panel',
    category: 'power',
    description: 'High-efficiency solar energy harvesting panel for outdoor solar rovers and autonomous weather stations.',
    dimensions: [110, 3, 60],
    defaultColor: '#0F172A',
    approxPriceUsd: 4.0,
    tags: ['solar', 'solar panel', 'clean energy', 'outdoor', 'harvester', 'green energy'],
    specs: {
      workingVoltage: '5.0V',
      workingCurrent: '200mA (1 Watt peak)',
    },
    meshType: 'solar_panel',
    pins: [
      { id: 'SOLAR_POS', name: 'Solar + (Red)', type: 'power-5v', position: 'right', color: '#EF4444' },
      { id: 'SOLAR_NEG', name: 'Solar - (Black)', type: 'ground', position: 'right', color: '#1F2937' },
    ]
  }
];
